bin/loxcan
composer.json
composer.lock
config/commands.yaml
config/reporters.yaml
config/usecases.yaml
src/Command/ScanCommand.php
src/Exception/InvalidConfigurationException.php
src/Reporter/EnvironmentTrait.php
src/Reporter/GitHub/GitHubClient.php
src/Reporter/GitHub/GitHubException.php
src/Reporter/GitHub/GitHubMarkdownBuilder.php
src/Reporter/GitHub/GitHubReporter.php
src/Reporter/ReporterInterface.php
src/UseCase/ReportUseCase.php
tests/Reporter/GitHub/GitHubClientTest.php
tests/Reporter/GitHub/GitHubMarkdownBuilderTest.php
tests/Reporter/GitHub/GitHubReporterTest.php

✨ GitHub Reporter

---

src/Git/Git.php
src/Model/FileDiff.php
src/Scanner/Composer/ComposerLockParser.php
src/Scanner/Composer/ComposerScanner.php
src/Scanner/ScannerInterface.php
src/Scanner/ScannerResolver.php
src/UseCase/ScanUseCase.php
tests/Git/GitTest.php
tests/Scanner/ScannerResolverTest.php
tests/UseCase/ScanUseCaseTest.php

🐛 Fix the files in child directories never has been scanned

---

README.md
config/scanners.yaml
src/Scanner/AbstractPackagePool.php
src/Scanner/Composer/ComposerPackagePool.php
src/Scanner/Npm/NpmLockParser.php
src/Scanner/Npm/NpmPackagePool.php
src/Scanner/Npm/NpmScanner.php
tests/Scanner/AbstractPackagePoolTest.php
tests/Scanner/Composer/ComposerPackagePoolTest.php

✨ npm scanner support

---

README.md
composer.json
composer.lock
config/scanners.yaml
config/versioning.yaml
src/Scanner/Cargo/CargoLockParser.php
src/Scanner/Cargo/CargoPackagePool.php
src/Scanner/Cargo/CargoScanner.php
src/Versioning/SemVer/SemVerVersion.php
src/Versioning/SemVer/SemVerVersionComparator.php
src/Versioning/SemVer/SemVerVersionParser.php
tests/Scanner/Cargo/CargoLockParserTest.php
tests/Scanner/Cargo/CargoPackagePoolTest.php
tests/Scanner/Cargo/CargoScannerTest.php
tests/Versioning/SemVer/SemVerVersionComparatorTest.php
tests/Versioning/SemVer/SemVerVersionParserTest.php

✨ Cargo (Cargo.lock) scanner support

---

config/reporters.yaml
src/Reporter/GitHub/GitHubClient.php
src/Reporter/GitHub/GitHubComment.php
src/Reporter/GitHub/GitHubReporter.php
src/Reporter/GitHub/GitHubUser.php
src/Reporter/GitHub/GitHubUserPool.php
tests/Reporter/GitHub/GitHubClientTest.php
tests/Reporter/GitHub/GitHubReporterTest.php
tests/Reporter/GitHub/GitHubUserPoolTest.php

🩹 Update the previous comment rather than creating a new one

---

src/Command/ScanCommand.php
src/Reporter/GitHub/GitHubMarkdownBuilder.php
tests/Reporter/GitHub/GitHubMarkdownBuilderTest.php

🐛 Fix Command & Reporter to support UNKNOWN version diff

---

composer.json
composer.lock
config/scanners.yaml
src/Scanner/Yarn/YarnLockParser.php
src/Scanner/Yarn/YarnPackagePool.php
src/Scanner/Yarn/YarnScanner.php
tests/Scanner/Yarn/YarnLockParserTest.php
tests/Scanner/Yarn/YarnPackagePoolTest.php
tests/Scanner/Yarn/YarnScannerTest.php

✨ Yarn (yarn.lock) scanner support

---

composer.json
composer.lock
src/Git/Git.php

🩹 Support Windows (CRLF) environment

---

src/Scanner/Yarn/YarnLockParser.php

🐛 Fix yarn.lock parser is not working properly

---

.github/workflows/php.yml

👷 Run CI on PRs from others

---

.github/workflows/action.yml
README.md
action.yml

🔧 Use default input to provide details of pull requests

---

action.yml
entrypoint.sh

🐛 Fix the reporter is not working on organisation repos

---

README.md
config/scanners.yaml
src/Scanner/Pnpm/PnpmLockParser.php
src/Scanner/Pnpm/PnpmPackagePool.php
src/Scanner/Pnpm/PnpmScanner.php
tests/Scanner/Pnpm/PnpmLockParserTest.php
tests/Scanner/Pnpm/PnpmPackagePoolTest.php
tests/Scanner/Pnpm/PnpmScannerTest.php

✨ pnpm support

---

README.md

📝 Fix uses clause in the example on readme

---

src/Command/ScanCommand.php
src/Git/Git.php
src/UseCase/ScanUseCase.php
tests/Git/GitTest.php

✨ Support scanning uncommitted changes

---

config/scanners.yaml
src/Scanner/Pip/PipLockParser.php
src/Scanner/Pip/PipPackagePool.php
src/Scanner/Pip/PipScanner.php
src/Versioning/Simple/SimpleVersion.php
src/Versioning/Simple/SimpleVersionParser.php
tests/Scanner/Pip/PipLockParserTest.php
tests/Scanner/Pip/PipPackagePoolTest.php
tests/Scanner/Pip/PipScannerTest.php

✨ Support pip (Pipfile.lock)

---

src/Command/ScanCommand.php
src/Reporter/GitHub/GitHubMarkdownBuilder.php
src/Versioning/CompatibilityAwareInterface.php
src/Versioning/Composer/ComposerVersion.php
src/Versioning/HasSemVerLikeCompatibility.php
src/Versioning/SemVer/SemVerVersion.php
src/Versioning/VersionDiff.php
tests/Command/ScanCommandTest.php
tests/Reporter/GitHub/GitHubMarkdownBuilderTest.php

✨ Emphasize version diff that has breaking changes

---

Dockerfile

fix: Fix Git accesses are failing

---

.github/workflows/docker.yml
action.yml

build: Push images to GHCR and use them on action

---

.github/workflows/php.yml
src/Scanner/Pnpm/PnpmLockParser.php
tests/Scanner/Pnpm/PnpmLockParserTest.php

Solve this issue.
https://github.com/siketyan/loxcan/issues/101

fix: pnpm nested versioning pattern

---

config/reporters.yaml
config/usecases.yaml
src/Command/ScanCommand.php
src/Exception/InvalidReporterException.php
src/Reporter/Console/ConsoleReporter.php
src/Reporter/GitHub/GitHubReporter.php
src/Reporter/MarkdownBuilder.php
src/Reporter/ReporterInterface.php
src/Reporter/ReporterResolver.php
src/UseCase/ReportUseCase.php
tests/Command/ScanCommandTest.php
tests/Reporter/Console/ConsoleReporterTest.php
tests/Reporter/GitHub/GitHubMarkdownBuilderTest.php
tests/Reporter/GitHub/GitHubReporterTest.php

feat: Introduce console reporter, enabled by default
